site_deployed_url: /Documentation 
# this property is used to fix issues caused by deploying on github without a custom/sub domain. Instead of the root of the website being after the .com,  
# its after .com/repo-name/ which causes absolute paths to incorrectly navigate.
#baseurl: "/Documentation"
#url: "https://intellitect.github.io"

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: Intellitect Documentation
# this appears on the top navigation bar next to the home button

site_title: Intellitect
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: Intellitect
# this appears in the footer

disqus_shortname:
# if you're using disqus for comments, add the shortname here. if not, leave this value blank.

search_enabled: true
# if you do not want search comment out the previous line

# google_analytics: UA-66296557-1
# if you have google-analytics ID, put it in. if not, edit this value to blank.

host: 127.0.0.1
# the preview server used. Leave as is.

port: 4000
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

exclude:
  - .idea/
  - .gitignore
  - vendor
# these are the files and directories that jekyll will exclude from the build

feedback_subject_line: Intellitect Documentation Feedback

feedback_email: TODO@Intellitect.com
# used as a contact email for the Feedback link in the top navigation bar

# feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed

# feedback_text: "Need help?"
# if you uncomment the previous line, it changes the Feedback text

# feedback_link: "http://helpy.io/"
# if you uncomment the previous line, it changes where the feedback link points to

highlighter: rouge
# library used for syntax highlighting

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways

plugins:
  - jekyll-redirect-from

collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: home_sidebar
      topnav: topnav

sidebars:
- home_sidebar
- carbon_sidebar
- trellis_sidebar
- myriad_sidebar

description: "Intended as documentation for Intellitect software services."

github: [metadata]

theme: jekyll-theme-cayman
